### PR TITLE
Sprint

### PR DESCRIPTION
**Pull request by hab278**
A simple cucumber story that lets an admin create a new language.

After the creation of a new language in a given group. Admin can add a description, change property value, set a new property value, and add an example. Finally the admin saves his language.

Comes with many bug fixes:
- https://github.com/linguisticexplorer/Linguistic-Explorer/commit/15d6987dc93edfabd80f78a29ed8ca1197af46ad - Fixes JS issue where the create example modal wasn't popping up even after adding a new value
- https://github.com/linguisticexplorer/Linguistic-Explorer/commit/8ef0dce11c1460d0f1124e0bacdabc8b3acab1e8 - Fixes issue where the language's description wasn't being saved
- https://github.com/linguisticexplorer/Linguistic-Explorer/commit/7043b03150d20d4a497f13914c4c37273cb765eb - Fixes major issue which allows memberships to be used as a resource
- https://github.com/linguisticexplorer/Linguistic-Explorer/commit/cd8a677e509d19ccc65811a56df670c6299decec - Fixes issue where haml was printing ruby code as literal
- https://github.com/linguisticexplorer/Linguistic-Explorer/commit/cd8a677e509d19ccc65811a56df670c6299decec - Gives Admin full privileges. The issue is still at large, code attempts to get resource of a relationship, but will be fixed in next sprint...

### CODE REVIEW

**Comment by dej611** [comment]
It looks that there's some issue with some dependency. Does it work on your machine?

**Comment by hab278** [comment]
@dej611 That's strange, I hadn't changed the Gemfile. I'll rerun the tests on Travis and see what the issue is with alphabetical_paginate.

**Comment by hab278** [comment]
@dej611 Cool, Travis is using some new platform for precise builds, comes with an older version of bundler. Travis is still failing, but this time for the same reason as master. Do you want me to apply the fix or should I pull that from origin?

**Comment by hab278** [comment]
@dej611 I might just apply the fix myself.

**Comment by dej611** [comment]
I think if you find the fix for this branch then it should be ok. Travis will pass and I'll happily merge.

**Comment by dej611** [comment]
Can you please merge the latest sprint and see if it passes?
The latest sprint passes all the `rspec` tests.

**Comment by dej611** [comment]
I believe that `phantomjs` error is due to some issues outside of our control, but perhaps there's a workaround.
From some research I found that [Travis-CI has phantom version 1.9.8 installed already](https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-74104694) - waiting to migrate to 2.0 - so if you're asking another version (as it does by default => `1.9.7`) it will poke the BitBucket CDN which may have some issues.
In particular there are 2 issues with the CDN: [version `1.9.7` doesn't exist there so a 403 message is downloaded and that stops the process](https://github.com/colszowka/phantomjs-gem/pull/35), and sometimes [the CDN will simply drop the calls because of anti-DDOS protection](https://github.com/Medium/phantomjs/issues/458).

The solutions are two:
- Use the same version as Travis-CI does on their environment ([I used this in the patch branch](https://github.com/linguisticexplorer/Linguistic-Explorer/blob/patch/Gemfile#L136))
- [`wget` phantomjs](https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-177592725) from another trusted source.

I vote for the former.

**Comment by hab278** [comment]
@dej611 I agree with you, I think that's the best immediate option.

**Comment by dej611** [comment]
Great.

**Pull request merged**
